
// Model for table data
export class TableData {

  constructor(
    public column1?: string,
    public column2?: string,
    public column3?: string,
    public column4?: string,
    public column5?: string,
    public column6?: string,
    public column7?: string,
    public column8?: string,
    public column9?: string,
    public column10?: string,
    public column11?: string,
    public column12?: string,
    public column13?: string,
    public column14?: string,
    public column15?: string,
    public column16?: string,
    public column17?: string,
    public column18?: string,
    public column19?: string,
    public column20?: string,
    public column21?: string,
    public column22?: string,
    public column23?: string,
    public column24?: string,
    public column25?: string,
    public column26?: string,
    public column27?: string,
    public column28?: string,
    public column29?: string,
    public column30?: string,
    public column31?: string,
    public column32?: string,
    public column33?: string,
    public column34?: string,
    public column35?: string,
    public column36?: string,
    public column37?: string,
    public column38?: string,
    public column39?: string,
    public column40?: string,
    public column41?: string,
    public column42?: string,
    public column43?: string,
    public column44?: string,
    public column45?: string,
    public column46?: string,
    public column47?: string,
    public column48?: string,
    public column49?: string,
    public column50?: string,
    public column51?: string,
    public column52?: string,
    public column53?: string,
    public column54?: string,
    public column55?: string,
    public column56?: string,
    public column57?: string,
    public column58?: string,
    public column59?: string,
    public highlight?: string,
    public retiredConcept?: string
  ) { }

}