#
# Spring Properties
#
spring:
    # Application Properties
    application:
        name: evsexplore
    # JSON Formatting Properties
    jackson:
        serialization:
            INDENT_OUTPUT: true
    # jmx
    jmx:
        enabled: false
    # Cloud Properties
    cloud:
      gateway:
        routes:
          - id: evsrestapi
            uri: ${EVS_REST_API_URL:http://localhost:8082/api/v1}
            predicates:
              - Path=/api/v1/**

#
# Server Properties
#
server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024   
    port: ${NCI_EVSEXPLORE_SERVER_PORT:4200}
    servlet:
       context-path: ${NCI_EVSEXPLORE_CONTEXT_PATH:/evsexplore}

#
# Management Properties
#
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health,hystrix.stream

#
# Logging Properties
#
logging:
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
        org.springframework.boot: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT:WARN}
        gov.nih.nci.evsexplore.web: ${LOGGING_LEVEL_GOV_EVSEXPLORE:INFO}

#
# EVS Explore properties
#
gov:
  nih:
    nci:   
      evsexplore:               
          web:
            evsApibasePath: ${EVS_API_BASE_PATH:http://localhost:8082}
            uiLicense: ${UI_LICENSE:ui-license}
