#
# Spring Properties
#
spring:
    # Application Properties
    application:
        name: evsexplore
    # JSON Formatting Properties
    jackson:
        serialization:
            INDENT_OUTPUT: true
    # jmx
    jmx:
        enabled: false        
    
#
# Server Properties
#
server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024   
    port: ${NCI_EVSEXPLORE_SERVER_PORT:8443}
    servlet:
       context-path: ${NCI_EVSEXPLORE_CONTEXT_PATH:/evsexplore}

#
# Management Properties
#
management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health,hystrix.stream

# Zuul Properties
#
# The sensitiveHeaders are a blacklist, and the default is not empty. 
# Consequently, to make Zuul send all headers (except the ignored ones), 
# you must explicitly set it to the empty list. 
#
zuul:
  routes:
    evsrestapi:
      path: /api/v1/**
      sensitiveHeaders:
      url: ${EVS_REST_API_URL:http://localhost:8082/api/v1}
   
#
# Logging Properties
#
logging:
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
        org.springframework.boot: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT:WARN}        
        gov.nih.nci.evsexplore.web: ${LOGGING_LEVEL_GOV_EVSEXPLORE:INFO}

#
# EVS Explore properties
#
gov:
  nih:
    nci:   
      evsexplore:               
          web:
            evsApibasePath: ${EVS_API_BASE_PATH:http://localhost:8082}
            uiLicense: ${UI_LICENSE:ui-license}
